# Default values for formapp-stack
# This is a YAML-formatted file.

# Global settings
global:
  namespace: kro-apps

# FormApp Instance Configuration
formapp:
  # Instance metadata
  name: formapp-stack
  namespace: kro-apps
  
  # Application configuration
  app:
    enabled: true
    name: form-app
    image: moses101/form-app:latest
    
    # HPA configuration
    hpa:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 65
      targetMemoryUtilizationPercentage: 70
    
    # Resource requests and limits
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "300m"
        memory: "1Gi"
    
    # Service configuration
    service:
      type: LoadBalancer
      port: 8086
      targetPort: 8086
    
    # Ingress configuration
    ingress:
      enabled: false
  
  # Database configuration
  database:
    enabled: true
    name: postgres
    image: bitnami/postgresql:12.1.0
    replicas: 1
    dbName: formdb
    username: postgres
    password: postgres
    
    # Resource requests and limits for database
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "2Gi"
    
    # Service configuration for database
    service:
      port: 5432
      targetPort: 5432
    
    # Persistent storage configuration
    storage:
      enabled: true
      storageClass: longhorn
      size: 3Gi
      accessMode: ReadWriteOnce

# Hook configurations
hooks:
  # Weight for pre-install hooks (CRD should be applied first)
  crd:
    weight: -10
  rgd:
    weight: -5