{{- if .Values.formapp.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.formapp.database.name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "formapp-stack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
spec:
  selector:
    app: {{ .Values.formapp.database.name }}
    app.kubernetes.io/name: {{ include "formapp-stack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.formapp.database.service.port }}
      targetPort: {{ .Values.formapp.database.service.targetPort }}
      name: postgres
{{- end }}
