{{- if .Values.formapp.database.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.formapp.name }}-postgres-init
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "formapp-stack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
data:
  init-db.sql: |
    CREATE TABLE IF NOT EXISTS submissions (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
{{- end }}
