# {{- if not (lookup "apiextensions.k8s.io" "CustomResourceDefinition" "" "formapps.kro.run") }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: formapps.kro.run
  # annotations:
  #   "helm.sh/hook": "pre-install,pre-upgrade"
  #   "helm.sh/hook-weight": "-1"
spec:
  group: kro.run
  names:
    kind: FormApp
    listKind: FormAppList
    plural: formapps
    singular: formapp
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                name:
                  type: string
                app:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    name:
                      type: string
                    image:
                      type: string
                    hpa:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: true
                        minReplicas:
                          type: integer
                          default: 2
                        maxReplicas:
                          type: integer
                          default: 10
                        targetCPUUtilizationPercentage:
                          type: integer
                          default: 70
                        targetMemoryUtilizationPercentage:
                          type: integer
                          default: 80
                    resources:
                      type: object
                      properties:
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                              default: "100m"
                            memory:
                              type: string
                              default: "128Mi"
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                              default: "500m"
                            memory:
                              type: string
                              default: "512Mi"
                    service:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                            - ClusterIP
                            - NodePort
                            - LoadBalancer
                            - ExternalName
                          default: "LoadBalancer"
                        port:
                          type: integer
                          default: 8086
                        targetPort:
                          type: integer
                          default: 8086                
                    ingress:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: false
                database:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    name:
                      type: string
                    image:
                      type: string
                      default: "bitnami/postgresql:12.1.0"
                    dbName:
                      type: string
                      default: "formdb"
                    username:
                      type: string
                      default: "postgres"
                    password:
                      type: string
                      default: "postgres"
                    replicas:
                      type: integer
                      default: 2
                    resources:
                      type: object
                      properties:
                        requests:
                          type: object
                          properties:
                            cpu:
                              type: string
                              default: "250m"
                            memory:
                              type: string
                              default: "256Mi"
                        limits:
                          type: object
                          properties:
                            cpu:
                              type: string
                              default: "500m"
                            memory:
                              type: string
                              default: "1Gi"
                    service:
                      type: object
                      properties:
                        port:
                          type: integer
                          default: 5432
                        targetPort:
                          type: integer
                          default: 5432
                    storage:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: true
                        storageClass:
                          type: string
                          default: "longhorn"
                        size:
                          type: string
                          default: "5Gi"
                        accessMode:
                          type: string
                          enum:
                            - ReadWriteOnce
                            - ReadOnlyMany
                            - ReadWriteMany
                          default: "ReadWriteOnce"
# {{- end }}
